// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOIsT2gE-7NlXRfNCb20RRkXynaxc6wg',
    appId: '1:345483270727:web:9dae5f26574fc95f0d2f62',
    messagingSenderId: '345483270727',
    projectId: 'questquill-e201b',
    authDomain: 'questquill-e201b.firebaseapp.com',
    storageBucket: 'questquill-e201b.appspot.com',
    measurementId: 'G-2GK5WNH2BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3ERJMANNjhrP6ZXALXbaZ68gX7IlYfc',
    appId: '1:345483270727:android:1c08c363136eb14d0d2f62',
    messagingSenderId: '345483270727',
    projectId: 'questquill-e201b',
    storageBucket: 'questquill-e201b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdB6lhDf1tc4hlQ62NiRc5FGM5DqSTJQ',
    appId: '1:345483270727:ios:7d7bf772bb83a2a30d2f62',
    messagingSenderId: '345483270727',
    projectId: 'questquill-e201b',
    storageBucket: 'questquill-e201b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdB6lhDf1tc4hlQ62NiRc5FGM5DqSTJQ',
    appId: '1:345483270727:ios:f8c012ee15410f090d2f62',
    messagingSenderId: '345483270727',
    projectId: 'questquill-e201b',
    storageBucket: 'questquill-e201b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
